// add a message for each data structure you want to serialize, 
// then specify a name and a type for each field in the message

edition = "2023";

// when this is compiled c++ will put it in a namespace matching the package name
package tutorial;

message Person {
    // fields can either be singular or repeated
    // singular is default and a type specific default will be set into it if not set
    // repeated means that the field may be repeated any number of times and the order of the values will be preserved (like an ongoing array)
  string name = 1;
  int32 id = 2;
  string email = 3;

  enum PhoneType {
    PHONE_TYPE_UNSPECIFIED = 0;
    PHONE_TYPE_MOBILE = 1;
    PHONE_TYPE_HOME = 2;
    PHONE_TYPE_WORK = 3;
  }

  message PhoneNumber {
    string number = 1;
    PhoneType type = 2;
  }

  repeated PhoneNumber phones = 4;
}

message AddressBook {
  repeated Person people = 1;
}
